# Generated by Django 3.2.5 on 2021-07-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_tie_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'test',
            },
        ),
    ]
