# Generated by Django 3.2.5 on 2021-07-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', 'provinceID_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='tie',
            name='indusID',
            field=models.IntegerField(default=0, verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='tie',
            name='provID',
            field=models.IntegerField(default=0, verbose_name='地域'),
        ),
    ]
