# Generated by Django 3.2.5 on 2021-07-21 08:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', 'industry_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tie',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='replyTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最新回复时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(max_length=30, null=True, verbose_name='推荐人'),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
