# Generated by Django 3.2.5 on 2021-07-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.department')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('studentID', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('referrer', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.city')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.industry')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.major')),
            ],
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('createdTime', models.DateTimeField()),
                ('replyTime', models.DateTimeField()),
                ('access', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.user')),
                ('relatedActivity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.activity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('relatedTie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.tie')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.city'),
        ),
    ]
