# Generated by Django 3.2.5 on 2021-07-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_auto_20210721_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=200, verbose_name='邮箱'),
        ),
    ]
