# Generated by Django 3.2.5 on 2021-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210721_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsheet',
            options={'verbose_name': '学生表单', 'verbose_name_plural': '导入学生表单'},
        ),
        migrations.AddField(
            model_name='studentsheet',
            name='hasBeenProceeded',
            field=models.BooleanField(default=False),
        ),
    ]
