# Generated by Django 3.2.5 on 2021-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210710_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name1',
            field=models.CharField(default='NotPointed', max_length=30),
        ),
    ]
