# Generated by Django 3.2.5 on 2021-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_department_name1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '院系', 'verbose_name_plural': '院系'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': '行业', 'verbose_name_plural': '行业'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': '专业', 'verbose_name_plural': '专业'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '楼层', 'verbose_name_plural': '楼层'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='tie',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='name1',
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=200, verbose_name='详细地点'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(max_length=200, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='content',
            field=models.TextField(max_length=200, verbose_name='内容'),
        ),
        migrations.RemoveField(
            model_name='tie',
            name='tag',
        ),
        migrations.AddField(
            model_name='tie',
            name='tag',
            field=models.ManyToManyField(to='alumni.Tag', verbose_name='所属标签'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(verbose_name='届次'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(max_length=30, verbose_name='推荐人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentID',
            field=models.CharField(max_length=20, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名'),
        ),
    ]
