# Generated by Django 3.2.5 on 2021-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay',
            field=models.TextField(default='', max_length=30, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='replyTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最新回复时间'),
        ),
    ]
