# Generated by Django 3.2.5 on 2021-07-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20210722_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='问题描述')),
            ],
            options={
                'verbose_name': '注册问题',
                'verbose_name_plural': '注册问题',
            },
        ),
        migrations.AlterModelOptions(
            name='studentsheet',
            options={'verbose_name': '学生表单', 'verbose_name_plural': '学生表单'},
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='选项描述')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.question')),
            ],
        ),
    ]
