# Generated by Django 3.2.5 on 2021-07-26 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20210726_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
