# Generated by Django 3.2.5 on 2021-07-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20210723_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rightChoice',
            field=models.IntegerField(default=0, verbose_name='正确选项'),
        ),
    ]
