# Generated by Django 3.2.5 on 2021-07-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20210710_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.city', verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.department', verbose_name='所属院系'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='relatedTie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.tie', verbose_name='相关帖'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='access',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.user', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='createdTime',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='relatedActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.activity', verbose_name='相关活动'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='replyTime',
            field=models.DateTimeField(verbose_name='最新回复时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.city', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.department', verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.industry', verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.major', verbose_name='专业'),
        ),
    ]
