# Generated by Django 3.2.5 on 2021-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20210710_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='DEFAULT', max_length=30, verbose_name='标题'),
        ),
    ]
