# Generated by Django 3.2.5 on 2021-07-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_reply_replythumbnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.user')),
            ],
        ),
    ]
