# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20210724_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='hidden', max_length=20, verbose_name='性别'),
        ),
    ]
