# Generated by Django 3.2.5 on 2021-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20210712_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tie',
            name='tag',
        ),
        migrations.AddField(
            model_name='tie',
            name='tag',
            field=models.ManyToManyField(to='alumni.Tag', verbose_name='所属标签'),
        ),
    ]
