# Generated by Django 3.2.5 on 2021-07-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='city',
        ),
    ]
