# Generated by Django 3.2.5 on 2021-07-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='alumni.student', verbose_name='关联学生'),
            preserve_default=False,
        ),
    ]
