# Generated by Django 3.2.5 on 2021-07-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_remove_activity_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tie',
            name='tag',
        ),
    ]
