# Generated by Django 3.2.5 on 2021-07-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_user_stu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='studentID',
        ),
    ]
