# Generated by Django 3.2.5 on 2021-07-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_remove_tie_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default='febblay', on_delete=django.db.models.deletion.CASCADE, to='alumni.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(db_column='f', default='北京', on_delete=django.db.models.deletion.CASCADE, to='alumni.province'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='relatedTie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.tie', verbose_name='相关帖'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.department', verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.user', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='tie',
            name='relatedActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.activity', verbose_name='相关活动'),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.industry', verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.student', verbose_name='关联学生'),
        ),
    ]
