# Generated by Django 3.2.5 on 2021-07-14 16:45

# Attention!!!!!!
# This module provided an example of student information
# When in real situation, the student sheet should be uploaded through web, and this module should not be activated

from django.db import migrations, models
import django.db.models.deletion
import sqlite3
import os
from functionality.readexcel import decode
import csv

dbpath = './generator/data/city_version-4.sqlite'
sheetpath = './generator/data/example.xls'
departmentpath = './generator/data/school_department.csv'
schoolname = r'清华大学'


def department_init(apps, schema_editor): # import ../generator/data/city_version-4.sqlite into model city and province
    departmentList = []
    Department = apps.get_model('alumni', 'Department')
    with open(departmentpath) as f:
        f_csv = csv.reader(f)
        for row in f_csv:
            if row != []:
                if row[0] == schoolname:
                    departmentList = row
                    break

    print(departmentList)

    departmentNumUpperBound = len(departmentList)

    for i in range(2, departmentNumUpperBound):
        tmp = Department(name = departmentList[i])
        tmp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', 'city_init'),
    ]

    operations = [
        migrations.RunPython(department_init),
    ]
