# Generated by Django 3.2.5 on 2021-07-14 16:45

from django.db import migrations, models
import django.db.models.deletion
import sqlite3
import os

dbpath = './generator/data/city_version-4.sqlite'

def Industry_init(apps, schema_editor): # import ../generator/data/city_version-4.sqlite into model city and province
    Industry = apps.get_model('alumni', 'Industry')

    tmp = Industry(id = 0, name = '其他')
    tmp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', 'student_sheet_init'),
    ]

    operations = [
        migrations.RunPython(Industry_init),
    ]
