# Generated by Django 3.2.5 on 2021-07-14 16:45

from django.db import migrations, models
import django.db.models.deletion
import sqlite3
import os

dbpath = './generator/data/city_version-4.sqlite'

def ProvinceID_init(apps, schema_editor): # import ../generator/data/city_version-4.sqlite into model city and province
    if not os.path.exists(dbpath):
        print('no database detected')
    else:
        print('database detected!')
    conn = sqlite3.connect(dbpath)
    c = conn.cursor()

    ProvinceID = apps.get_model('alumni', 'ProvinceID')
    
    cursor = c.execute('SELECT * FROM province')

    for row in cursor:
        tmp = ProvinceID(name = row[1])
        tmp.save()
    
    print('Province_init finished')


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20210726_0039'),
    ]

    operations = [
        migrations.RunPython(ProvinceID_init),
    ]
